apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-cozezone-psql
  namespace: cozezone
spec:
  databases:
    mastodon_production: postgres
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: '11'
  teamId: acid
  users:
    mastodon_production_user: []
    postgres:
      - superuser
      - createdb
  volume:
    size: 8Gi
